name: Build Wbtc APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4

      - name: Setup GraalVM 17
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '17'
          distribution: 'graalvm'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Setup Gradle 8.0
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.0'

      - name: Build APK
        run: |
          cat build.gradle
          gradle wrapper --gradle-version 8.0
          chmod +x gradlew
          ./gradlew nativeBuild -Ptarget=android --stacktrace
          ./gradlew nativePackage -Ptarget=android --stacktrace

      - name: Upload APK
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Wbtc-apk
          path: |
            build/gluonfx/**/gvm/*.apk
            build/client/**/gvm/*.apk
            build/**/*.apk
